logging:
    level:
        root: INFO
        web: DEBUG
        org:
            hibernate: DEBUG
            springframework:
                web: TRACE
        com:
            freimanvs: DEBUG
server:
    port: 8085
spring:
    profiles:
        default: prod
        active: '@spring.profiles.active@'
    application:
        name: subscriptions
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        pool:
            enabled: true
#        generate-ddl: true
#        hibernate:
#            ddl-auto: update
#            ddl-auto: validate